repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: Python style guide enforcement
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]
